tools/linux/blk: create FAT FS if fail to mount
Signed-off-by: Bill Nguyen <bill.nguyen@unsw.edu.au>

diff --git a/tools/linux/blk/blk_client_init b/tools/linux/blk/blk_client_init
--- a/tools/linux/blk/blk_client_init
+++ b/tools/linux/blk/blk_client_init
@@ -6,8 +6,23 @@
 
 set -e
 
-if ! mount /dev/vda /mnt;
+BLOCK_DEV=/dev/vda
+MOUNT_POINT=/mnt
+
+if ! ls "$BLOCK_DEV" >/dev/null;
 then
-    echo "FAILED to mount virtio block device, powering down"
-    poweroff
+    echo "ERROR: virtio block device does not exist!"
+    exit 1
 fi
+
+if ! mount "$BLOCK_DEV" "$MOUNT_POINT";
+then
+    echo "WARNING: failed to mount block device, trying to create a FAT32 filesystem."
+    if ! mkdosfs -F 32 -n "virtio_block_dev" "$BLOCK_DEV";
+    then
+        echo "ERROR: cannot create FAT32 filesystem on block device."
+        exit 1
+    fi
+fi
+
+echo "$BLOCK_DEV" successfully mounted at "$MOUNT_POINT"
