tools/linux/blk: add missing mount in blk init
Signed-off-by: Bill Nguyen <bill.nguyen@unsw.edu.au>

diff --git a/tools/linux/blk/blk_client_init b/tools/linux/blk/blk_client_init
--- a/tools/linux/blk/blk_client_init
+++ b/tools/linux/blk/blk_client_init
@@ -15,4 +15,10 @@ then
     exit 1
 fi
 
+if ! mount "$BLOCK_DEV" "$MOUNT_POINT";
+then
+    echo "ERROR: failed to mount $BLOCK_DEV"
+    exit 1
+fi
+
 echo "$BLOCK_DEV" successfully mounted at "$MOUNT_POINT"
