add a new option to packrootfs that saves a file to the root as init rather than copying it to /etc/init.d
Signed-off-by: Anuraag <anuraag23.04@gmail.com>

diff --git a/tools/packrootfs b/tools/packrootfs
--- a/tools/packrootfs
+++ b/tools/packrootfs
@@ -5,7 +5,7 @@
 # SPDX-License-Identifier: BSD-2-Clause
 
 if [ $# -lt 2 ]; then
-    echo "Usage: $0 <rootfs> <tmpdir> [-o output_rootfs] [--startup files...] [--home files...] [--etc files...]"
+    echo "Usage: $0 <rootfs> <tmpdir> [-o output_rootfs] [--startup files...] [--home files...] [--etc files...] [--init init_file]"
     exit 1
 fi
 
@@ -15,6 +15,7 @@ startup_files=()
 home_files=()
 etc_files=()
 output_rootfs=""
+init_file=""
 
 shift 2
 while [[ $# -gt 0 ]]; do
@@ -39,6 +40,16 @@ while [[ $# -gt 0 ]]; do
                 etc_files+=("$1")
                 shift
             done
+            ;;
+        --init)
+            shift
+            if [[ $# -gt 0 ]]; then
+                init_file=$1
+                shift
+            else
+                echo "Error: --init option requires an argument."
+                exit 1
+            fi
             ;;
         -o)
             shift
@@ -82,6 +93,11 @@ done
 for file in "${etc_files[@]}"; do
     cp -- "$file" "$tmpdir/etc/$(basename "$file")"
 done
+
+if [[ "$init_file" != "" ]]; then
+    cp -- "$init_file" "$tmpdir/init"
+    chmod +x "$tmpdir/init"
+fi
 
 if [[ "$output_rootfs" == /* ]]; then
     final_output_path="$output_rootfs"
